# SwiftLint Configuration for Vivacity
# Aligned with .agents/CODING_STANDARDS.md

# Paths to lint
included:
  - Vivacity

excluded:
  - build
  - .build
  - Pods
  - DerivedData

# Rules
disabled_rules:
  - trailing_comma          # We allow trailing commas per coding standards
  - todo                    # TODOs are allowed during development
  - opening_brace           # SwiftFormat handles this
  - force_unwrapping        # Raw buffer parsing uses intentional force unwraps
  - for_where               # for/if is often clearer than for-where in scanner code

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - empty_count
  - explicit_init
  - contains_over_first_not_nil
  - first_where
  - implicit_return
  - joined_default_parameter
  - last_where
  - modifier_order
  - overridden_super_call
  - private_over_fileprivate
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

# Rule configurations
line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 600
  error: 1000

type_body_length:
  warning: 400
  error: 600

function_body_length:
  warning: 80
  error: 120

identifier_name:
  min_length:
    warning: 1
  max_length:
    warning: 60
  excluded:
    - id
    - fd
    - i
    - j
    - x
    - y

type_name:
  min_length:
    warning: 3
  max_length:
    warning: 50

large_tuple:
  warning: 3
  error: 4

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 2
  function_level:
    warning: 3

reporter: xcode
