import Foundation

// MARK: - Scan Source

/// Identifies which scan phase discovered a file.
enum ScanSource: String, Sendable, Codable {
    case fastScan = "Fast"
    case deepScan = "Deep"
}

// MARK: - Scan Event

/// Stream element emitted by scan services.
enum ScanEvent: Sendable {
    /// A recoverable file was found.
    case fileFound(RecoverableFile)
    /// Scan progress updated (0–1).
    case progress(Double)
    /// Exact deep-scan cursor checkpoint (bytes scanned).
    case checkpoint(UInt64)
    /// The scan phase completed.
    case completed
}

// MARK: - Recovery Confidence

/// Estimated chance that a file can be fully recovered.
enum RecoveryConfidence: String, Sendable, Codable {
    case high
    case medium
    case low

    /// Short label for UI display.
    var displayName: String {
        switch self {
        case .high: "High"
        case .medium: "Medium"
        case .low: "Low"
        }
    }

    /// VoiceOver-friendly label for the confidence indicator.
    var accessibilityLabel: String {
        "Recovery confidence: \(displayName)"
    }

    /// Explicit badge copy for scan result rows.
    var badgeText: String {
        "Recovery \(displayName)"
    }

    /// Short explanation shown on hover in the scan results list.
    var helpText: String {
        switch self {
        case .high:
            "High recovery confidence. The scan found strong signals that this file can be recovered cleanly."
        case .medium:
            "Medium recovery confidence. Recovery is plausible, but missing or damaged sections are still possible."
        case .low:
            "Low recovery confidence. The scan found weak or incomplete signals for this file."
        }
    }
}

/// Estimated likelihood that recovered output contains corruption artifacts.
enum CorruptionLikelihood: String, Sendable, Codable {
    case low
    case medium
    case high

    var displayName: String {
        switch self {
        case .low: "Low"
        case .medium: "Medium"
        case .high: "High"
        }
    }

    var accessibilityLabel: String {
        "Corruption risk: \(displayName)"
    }

    var badgeText: String {
        "Corruption \(displayName)"
    }

    var helpText: String {
        switch self {
        case .low:
            "Low corruption risk. This file looks likely to preview and recover without major issues."
        case .medium:
            "Medium corruption risk. The recovered file may contain missing frames, artifacts, or damaged sections."
        case .high:
            "High corruption risk. Expect a higher chance of visible damage, playback errors, or incomplete recovery."
        }
    }
}

// MARK: - Recoverable File

/// A file on disk that can potentially be recovered.
struct RecoverableFile: Identifiable, Hashable, Sendable, Codable {
    /// Unique identifier for this file.
    let id: UUID

    /// Original or generated file name (without extension).
    let fileName: String

    /// File extension (e.g. "jpg", "mp4").
    let fileExtension: String

    /// Broad category: image or video.
    let fileType: FileCategory

    /// Size of the file in bytes (estimated or exact).
    let sizeInBytes: Int64

    /// Byte offset on the source device where the file data begins.
    let offsetOnDisk: UInt64

    /// The signature that matched this file.
    let signatureMatch: FileSignature

    /// Which scan phase found this file.
    let source: ScanSource

    /// The original file path on the volume, if discovered via filesystem scan.
    var filePath: String?

    /// Whether the scanner could infer that the bytes are likely contiguous.
    /// `nil` means unknown.
    var isLikelyContiguous: Bool?

    /// Optional normalized confidence score (0...1) generated by deep scan quality checks.
    /// `nil` for fast-scan discoveries that do not use carving heuristics.
    var confidenceScore: Double?

    /// Optional ordered list of disk regions that should be concatenated to recover this file.
    /// When present and count > 1, the file is fragmented and requires multi-region assembly.
    /// `nil` means the file is a single contiguous region starting at `offsetOnDisk`.
    var fragmentMap: [FragmentRange]?

    init(
        id: UUID,
        fileName: String,
        fileExtension: String,
        fileType: FileCategory,
        sizeInBytes: Int64,
        offsetOnDisk: UInt64,
        signatureMatch: FileSignature,
        source: ScanSource,
        filePath: String? = nil,
        isLikelyContiguous: Bool? = nil,
        confidenceScore: Double? = nil,
        fragmentMap: [FragmentRange]? = nil
    ) {
        self.id = id
        self.fileName = fileName
        self.fileExtension = fileExtension
        self.fileType = fileType
        self.sizeInBytes = sizeInBytes
        self.offsetOnDisk = offsetOnDisk
        self.signatureMatch = signatureMatch
        self.source = source
        self.filePath = filePath
        self.isLikelyContiguous = isLikelyContiguous
        self.confidenceScore = confidenceScore
        self.fragmentMap = fragmentMap
    }

    // MARK: - Computed

    /// Human-readable file size string (e.g. "3.2 MB").
    var sizeFormatted: String {
        ByteCountFormatter.string(fromByteCount: sizeInBytes, countStyle: .file)
    }

    /// Full file name with extension (e.g. "IMG_2847.jpg").
    var fullFileName: String {
        "\(fileName).\(fileExtension)"
    }

    /// Derived recovery confidence based on scan source and contiguity hints.
    var recoveryConfidence: RecoveryConfidence {
        if let confidenceScore {
            switch confidenceScore {
            case 0.75...:
                return .high
            case 0.45...:
                return .medium
            default:
                return .low
            }
        }

        switch source {
        case .fastScan:
            // Catalog/filesystem hits generally preserve file boundaries and names.
            return isLikelyContiguous == false ? .medium : .high

        case .deepScan:
            // Raw carving is less certain; explicit contiguity raises confidence.
            if isLikelyContiguous == true {
                return .medium
            }
            if isLikelyContiguous == false {
                return .low
            }

            // Unknown contiguity: use discovered size as a weak confidence signal.
            return sizeInBytes > 0 ? .medium : .low
        }
    }

    /// Inverse signal of `recoveryConfidence`, surfaced as corruption risk in UI.
    var corruptionLikelihood: CorruptionLikelihood {
        switch recoveryConfidence {
        case .high:
            .low
        case .medium:
            .medium
        case .low:
            .high
        }
    }
}
